### ISSUE TITLE
Unknown hostname in connection open: '127.0.0.1' [condition = amqp:not-found]

### ISSUE THREAD

**Issue by imanzano** [novotnyr/qpid-embedded-junit4-rule#1]
When I tried to use it I got 

I tried several different configuration, but I always get the same error.

I use qpid client
` 
...
JmsConnectionFactory cf = JmsConnectionFactory(uri);
cf.createConnection()
...
`

I also try to set the binding to localhost or the ip of my machine.  I Got the same error.

`org.apache.qpid.jms.JmsResourceNotFoundException: Unknown hostname in connection open: '127.0.0.1' [condition = amqp:not-found]

	at org.apache.qpid.jms.provider.amqp.AmqpSupport.convertToException(AmqpSupport.java:151)
	at org.apache.qpid.jms.provider.amqp.AmqpSupport.convertToException(AmqpSupport.java:118)
	at org.apache.qpid.jms.provider.amqp.AmqpConnection.processRemoteClose(AmqpConnection.java:150)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.processUpdates(AmqpProvider.java:914)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.onData(AmqpProvider.java:824)
	at org.apache.qpid.jms.transports.netty.NettyTcpTransport$NettyTcpTransportHandler.channelRead0(NettyTcpTransport.java:539)
	at org.apache.qpid.jms.transports.netty.NettyTcpTransport$NettyTcpTransportHandler.channelRead0(NettyTcpTransport.java:532)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by novotnyr** [comment]
@imanzano Please provide a minimal working sample that shows this behaviour. Otherwise it is difficult to debug / see what is going on from the stack trace.
Thank you!
