### ISSUE TITLE
The "main" method fails to start the broker server

### ISSUE THREAD

**Issue by ndossantos-viseo** [novotnyr/qpid-embedded-junit4-rule#2]
When I run the `main` method in `EmbeddedInMemoryQpidBroker`, I have the following exception:

```
java.security.PrivilegedActionException: java.net.MalformedURLException: unknown protocol: classpath
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.qpid.server.SystemLauncher.startup(SystemLauncher.java:208)
	at com.github.novotnyr.qpid.junit4.EmbeddedInMemoryQpidBroker.start(EmbeddedInMemoryQpidBroker.java:32)
	at com.github.novotnyr.qpid.junit4.EmbeddedInMemoryQpidBroker.main(EmbeddedInMemoryQpidBroker.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
Caused by: java.net.MalformedURLException: unknown protocol: classpath
	at java.net.URL.<init>(URL.java:600)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.apache.qpid.server.SystemLauncher.populateSystemPropertiesFromDefaults(SystemLauncher.java:118)
	at org.apache.qpid.server.SystemLauncher.startupImpl(SystemLauncher.java:238)
	at org.apache.qpid.server.SystemLauncher.access$200(SystemLauncher.java:65)
	at org.apache.qpid.server.SystemLauncher$1.run(SystemLauncher.java:217)
	... 10 more
```

The problem comes from the SystemLauncher.populateSystemPropertiesFromDefaults metho where the following code is executed because the `initialProperties` parameter is null
```
initialPropertiesLocation = new URL(DEFAULT_INITIAL_PROPERTIES_LOCATION);
```

But `DEFAULT_INITIAL_PROPERTIES_LOCATION` is equal to "classpath:system.properties" and "classpath" is not recognized as protocol.

I think a workaround would be create a temporary properties file in the EmbeddedInMemoryQpidBroker class and add the `SystemConfig.INITIAL_SYSTEM_PROPERTIES_LOCATION` attribute with the path of the property file

**Comment by ndossantos-viseo** [comment]
Here is my modification in EmbeddedInMemoryQpidBroker.java to fix this problem:

```
public class EmbeddedInMemoryQpidBroker {

   ...

    private Map<String, Object> createSystemConfig() throws IllegalConfigurationException {
       ...

        final Map<String, Object> attributes = new HashMap<>();
        ...
        attributes.put(SystemConfig.INITIAL_SYSTEM_PROPERTIES_LOCATION, createSystemPropertyFile());
        return attributes;
    }

    private static String createSystemPropertyFile() {
        File file;
        try {
            final Path path = Files.createTempFile("system", ".properties");
            file = path.toFile();
            Files.write(path, Collections.singletonList(SystemConfig.PROPERTY_QPID_WORK + "=" + "target"), StandardCharsets.UTF_8);
            file.deleteOnExit();
        } catch (IOException e) {
            throw new IllegalConfigurationException("System property file not created", e);
        }
        return file.getAbsolutePath();
    }
}
```

**Comment by novotnyr** [comment]
Thanks your the report!

I am curious: how do you run the `main()` method? Is it from IDE (which one?) or is it from commandline?

The `classpath:` protocol -- when running from IntelliJ IDEA -- is handled by `org.apache.qpid.server.util.urlstreamhandler.classpath.Handler`. I am wondering how come this handler is not registered and Java fails with unregistered handler.

**Comment by hjohn** [comment]
Probably on a CI server, so command line, seeing something similar here in the CI but no problems locally

**Comment by MatthewRyanRead** [comment]
I just spent a while debugging this issue myself.  It seemed to be due to Maven restarting or forking the JVM, which resulted in deregistration of the `org.apache.qpid.server.util.urlstreamhandler.classpath.Handler` (despite `Handler._registered` remaining `true`).

I ended up solving it by calling this code before each test class executed (in a JUnit `BeforeAllCallback` extension):

```java
try {
    URL.setURLStreamHandlerFactory(protocol -> ("classpath".equals(protocol) ? new Handler() : null));
} catch (final Error ignored) {
    // Java is ridiculous and doesn't allow setting the factory if it's already been set
}
```
